//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.WSSmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSSmsService.SmsServiceSoap")]
    public interface SmsServiceSoap {
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 HelloWorldResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        BLL.WSSmsService.HelloWorldResponse HelloWorld(BLL.WSSmsService.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<BLL.WSSmsService.HelloWorldResponse> HelloWorldAsync(BLL.WSSmsService.HelloWorldRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 phones 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMsg", ReplyAction="*")]
        BLL.WSSmsService.SendMsgResponse SendMsg(BLL.WSSmsService.SendMsgRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMsg", ReplyAction="*")]
        System.Threading.Tasks.Task<BLL.WSSmsService.SendMsgResponse> SendMsgAsync(BLL.WSSmsService.SendMsgRequest request);
        
        // CODEGEN: 命名空间 http://tempuri.org/ 的元素名称 phones 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMsg2", ReplyAction="*")]
        BLL.WSSmsService.SendMsg2Response SendMsg2(BLL.WSSmsService.SendMsg2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMsg2", ReplyAction="*")]
        System.Threading.Tasks.Task<BLL.WSSmsService.SendMsg2Response> SendMsg2Async(BLL.WSSmsService.SendMsg2Request request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public BLL.WSSmsService.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(BLL.WSSmsService.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.WSSmsService.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(BLL.WSSmsService.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMsgRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMsg", Namespace="http://tempuri.org/", Order=0)]
        public BLL.WSSmsService.SendMsgRequestBody Body;
        
        public SendMsgRequest() {
        }
        
        public SendMsgRequest(BLL.WSSmsService.SendMsgRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMsgRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public SendMsgRequestBody() {
        }
        
        public SendMsgRequestBody(string phones, string content) {
            this.phones = phones;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMsgResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMsgResponse", Namespace="http://tempuri.org/", Order=0)]
        public BLL.WSSmsService.SendMsgResponseBody Body;
        
        public SendMsgResponse() {
        }
        
        public SendMsgResponse(BLL.WSSmsService.SendMsgResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMsgResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMsgResult;
        
        public SendMsgResponseBody() {
        }
        
        public SendMsgResponseBody(string SendMsgResult) {
            this.SendMsgResult = SendMsgResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMsg2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMsg2", Namespace="http://tempuri.org/", Order=0)]
        public BLL.WSSmsService.SendMsg2RequestBody Body;
        
        public SendMsg2Request() {
        }
        
        public SendMsg2Request(BLL.WSSmsService.SendMsg2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMsg2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string phones;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string content;
        
        public SendMsg2RequestBody() {
        }
        
        public SendMsg2RequestBody(string phones, string content) {
            this.phones = phones;
            this.content = content;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMsg2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMsg2Response", Namespace="http://tempuri.org/", Order=0)]
        public BLL.WSSmsService.SendMsg2ResponseBody Body;
        
        public SendMsg2Response() {
        }
        
        public SendMsg2Response(BLL.WSSmsService.SendMsg2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMsg2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMsg2Result;
        
        public SendMsg2ResponseBody() {
        }
        
        public SendMsg2ResponseBody(string SendMsg2Result) {
            this.SendMsg2Result = SendMsg2Result;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SmsServiceSoapChannel : BLL.WSSmsService.SmsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SmsServiceSoapClient : System.ServiceModel.ClientBase<BLL.WSSmsService.SmsServiceSoap>, BLL.WSSmsService.SmsServiceSoap {
        
        public SmsServiceSoapClient() {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SmsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.WSSmsService.HelloWorldResponse BLL.WSSmsService.SmsServiceSoap.HelloWorld(BLL.WSSmsService.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            BLL.WSSmsService.HelloWorldRequest inValue = new BLL.WSSmsService.HelloWorldRequest();
            inValue.Body = new BLL.WSSmsService.HelloWorldRequestBody();
            BLL.WSSmsService.HelloWorldResponse retVal = ((BLL.WSSmsService.SmsServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BLL.WSSmsService.HelloWorldResponse> BLL.WSSmsService.SmsServiceSoap.HelloWorldAsync(BLL.WSSmsService.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<BLL.WSSmsService.HelloWorldResponse> HelloWorldAsync() {
            BLL.WSSmsService.HelloWorldRequest inValue = new BLL.WSSmsService.HelloWorldRequest();
            inValue.Body = new BLL.WSSmsService.HelloWorldRequestBody();
            return ((BLL.WSSmsService.SmsServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.WSSmsService.SendMsgResponse BLL.WSSmsService.SmsServiceSoap.SendMsg(BLL.WSSmsService.SendMsgRequest request) {
            return base.Channel.SendMsg(request);
        }
        
        public string SendMsg(string phones, string content) {
            BLL.WSSmsService.SendMsgRequest inValue = new BLL.WSSmsService.SendMsgRequest();
            inValue.Body = new BLL.WSSmsService.SendMsgRequestBody();
            inValue.Body.phones = phones;
            inValue.Body.content = content;
            BLL.WSSmsService.SendMsgResponse retVal = ((BLL.WSSmsService.SmsServiceSoap)(this)).SendMsg(inValue);
            return retVal.Body.SendMsgResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BLL.WSSmsService.SendMsgResponse> BLL.WSSmsService.SmsServiceSoap.SendMsgAsync(BLL.WSSmsService.SendMsgRequest request) {
            return base.Channel.SendMsgAsync(request);
        }
        
        public System.Threading.Tasks.Task<BLL.WSSmsService.SendMsgResponse> SendMsgAsync(string phones, string content) {
            BLL.WSSmsService.SendMsgRequest inValue = new BLL.WSSmsService.SendMsgRequest();
            inValue.Body = new BLL.WSSmsService.SendMsgRequestBody();
            inValue.Body.phones = phones;
            inValue.Body.content = content;
            return ((BLL.WSSmsService.SmsServiceSoap)(this)).SendMsgAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BLL.WSSmsService.SendMsg2Response BLL.WSSmsService.SmsServiceSoap.SendMsg2(BLL.WSSmsService.SendMsg2Request request) {
            return base.Channel.SendMsg2(request);
        }
        
        public string SendMsg2(string phones, string content) {
            BLL.WSSmsService.SendMsg2Request inValue = new BLL.WSSmsService.SendMsg2Request();
            inValue.Body = new BLL.WSSmsService.SendMsg2RequestBody();
            inValue.Body.phones = phones;
            inValue.Body.content = content;
            BLL.WSSmsService.SendMsg2Response retVal = ((BLL.WSSmsService.SmsServiceSoap)(this)).SendMsg2(inValue);
            return retVal.Body.SendMsg2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<BLL.WSSmsService.SendMsg2Response> BLL.WSSmsService.SmsServiceSoap.SendMsg2Async(BLL.WSSmsService.SendMsg2Request request) {
            return base.Channel.SendMsg2Async(request);
        }
        
        public System.Threading.Tasks.Task<BLL.WSSmsService.SendMsg2Response> SendMsg2Async(string phones, string content) {
            BLL.WSSmsService.SendMsg2Request inValue = new BLL.WSSmsService.SendMsg2Request();
            inValue.Body = new BLL.WSSmsService.SendMsg2RequestBody();
            inValue.Body.phones = phones;
            inValue.Body.content = content;
            return ((BLL.WSSmsService.SmsServiceSoap)(this)).SendMsg2Async(inValue);
        }
    }
}
